version: '3.3'
services:
  db:
    image: postgres:13.3-alpine    
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  
  frontend:
    image: alexeynickulin/foodgram-frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  backend:
    image: alexeynickulin/foodgram-backend:latest
    restart: always
    ports: 
      - 8000:8000
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - frontend
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - media_value:/var/html/media/
      - static_value:/var/html/static/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      
      
volumes:
  postgres_data:
  static_value:
  media_value: